### ISSUE TITLE
Data Sample - Diversity: Coupe

### ISSUE THREAD

**Issue by jwood36** [Jsmit132/CIS255_Vehicle#2]
Per instructions, diversify your Coupe data sample.

**Comment by Jsmit132** [comment]
My apologies I struggled with finding coupes, specifically for Ford and Doge. I am correct in that we are limited to carvana.com for our searches? I will do more research tonight

**Comment by jwood36** [comment]
u are limited to carvana but refer to the exclusion instructions for variation guidance.

**Comment by Jsmit132** [comment]
Okay will do thanks for responding

**Comment by Jsmit132** [comment]
Revised Honda Coupe Entry, Does this close the issue?
