### ISSUE TITLE
Class - Static Creators

### ISSUE THREAD

**Issue by jwood36** [Jsmit132/CIS255_Vehicle#29]
your Static methods are defined separately from your instantiable methods.

Typically it does not matter whether they are Instance or Static, only Scope and Signature.

Consolidate your method signatures in the UML to be just Scope and Signature based; this includes the Constructors.  It is either Field or Method groupings.

**Comment by Jsmit132** [comment]
Update Vehicle_UML_JSmith132 based on Class - Static Creators #29
