### ISSUE TITLE
UML - Redesign

### ISSUE THREAD

**Issue by jwood36** [Jsmit132/CIS255_Vehicle#3]
UML Notation needs to reflect inheritance, not data-points.

You need to take your sample data and observe which data points are Object-based vs Data-based.  Data-based are more attributes that are not specific to any manufacturer, model, or type.

	- Based on the Spreadsheet, map out a Instantiable Object Class Inheritance UML Design.
		> This Design should be only the Object Names, do not represent Members or Primitive Types
		> Instantiable Objects include: Class, Abstract Class, and Interface
	- Add the High-Level UML Class Notation Image (Class Names ONLY) to the appropriate folder in your Repository

**Comment by Jsmit132** [comment]
Updated UML design, Does this close the issue?
