### ISSUE TITLE
Class - File Handler

### ISSUE THREAD

**Issue by jwood36** [Jsmit132/CIS255_Vehicle#34]
>     * Create a File Handler to output the Storage Class to a File
>         > File should be a simple CSV, with a Header Row
>         > Each row will be terminated with a CRLF or New-Line character
>         > File Extension: csv
>         > Delimiter Character: | (pipe symbol)

**Comment by Jsmit132** [comment]
Revised code in VehicleStorage to use New-Line character in place of writer.newline()
