### ISSUE TITLE
UML - Class Design

### ISSUE THREAD

**Issue by jwood36** [Jsmit132/CIS255_Vehicle#4]
There needs to be one "Page" in the Visio file for each of your classes (including Abstract).

Each of these Pages need to be equivalently exported as an Image into the appropriate folder.

**Comment by Jsmit132** [comment]
Im confused, in the class call you showed us the UML design along the lines of what I submitted with the rectangles with only the object names. Is "Page" supposed to be the details like in other UML's with variables underneath the object name? If not then does this tie into issue 3?
